#!/usr/bin/env bash

QEMU_CUSTOM=${QEMU_SRCDIR:+$QEMU_SRCDIR/build/qemu-system-aarch64}
QEMU=${QEMU_CUSTOM:-"/cuttlefish/bin/aarch64-linux-gnu/qemu/qemu-system-aarch64"}
ARGS="$@"

$QEMU $ARGS $EXTRA_QEMU_ARGS
